services:
  # ---------------- BACKEND ----------------
  - type: web
    name: backend-service
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true

  # ---------------- FRONTEND ----------------
  - type: web
    name: frontend-service
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist   # change if using Next.js -> .next or out
    autoDeploy: true
